### ISSUE TITLE
Hdmi output doesn't work

### ISSUE THREAD

**Issue by wlsantanna** [Staby2000/Hackintosh_7572_config#1]
Hi,

First thank you, I finally got a functional Hackintosh with your clover files. Everything is working fine except HDMI output, it doesn't appear image. Do it work for you? I'm using same DELL 7572 16GB Model. Thank you!

**Comment by Staby2000** [comment]
Re:

Maybe you can try to delete “-lilubetaall” or “lilucpu=8” at the Arguments in your config.plist. Since I don’t have demand for HDMI output, so good luck to you :)

[cid:07F09842-15A6-4FCE-BEFD-38F57707D62B]

On Dec 17, 2019, at 7:42 PM, wlsantanna <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

First thank you, I finally got a functional Hackintosh with your clover files. Everything is working fine except HDMI output, it doesn't appear image. Do it work for you? I'm using same DELL 7572 16GB Model. Thank you!
